name: student_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  file_picker: ^10.3.7
  fl_chart: ^1.1.1
  image_picker: ^1.0.4
  url_launcher: ^6.1.10
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.10.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/icon_background.png" # or path to background image
  adaptive_icon_foreground: "assets/images/icon_foreground.png" # optional
